### ISSUE TITLE
WorldGuard Region Templates

### ISSUE THREAD

**Issue by nomadjimbob** [STEMMechanics/STEMCraft-Core#64]
A region template feature would be an advantage and save running multiple commands each time.

For example, a town region would have several region flags set such as a title/subtitle/block placing?/etc, arenas would also be similar but allow PVP, workshops are again similar but would also add 2 groups <workshop> and <workshop>_active, adding the <workshop>_active to the member list of the region. When removing the region, these 2 groups would need to be deleted.

This could be done using a new config setup?

```yaml
region_templates:
    town:
        flags:
            title: "&e{title}"
    workshop:
        flags:
            title: "&4{title}"
            subtitle: "&4Workshop region"
        commands:
            create:
            - lp addgroup {id}
            - lp addgroup {id}_active
            - rg addmember {id} -w {world} g:{id}_active
            remove:
            - lp deletegroup {id}
            - lp deletegroup {id}_active
```

`{id}` = Region ID
`{title}` = Region ID prettied. Text before and including the first `_` character are ignored
`{world}` = The regions world name
